### PR TITLE
Upgrade to TwilioVideo v3 on iOS

### PR DESCRIPTION
**Pull request by steelbrain**
- [x] Upgrade TwilioVideo to v3 on iOS
- [x] Upgrade TwilioVideo on Android 
- [x] Resolve conflicts with Data channel changes
- [x] Fix audio methods on iOS post upgrade

### CODE REVIEW

**Comment by stevelizcano** [comment]
How can I integrate this now @steelbrain into my project using your branch/commit?  I would love to get started with this while we wait for the maintainer to merge.

**Comment by steelbrain** [comment]
@stevelizcano This PR does not yet include data channel support, like in master. Just a headsup.

If you want to use this in your project you can do

```
yarn remove react-native-twilio-video-webrtc
yarn add https://github.com/steelbrain/react-native-twilio-video-webrtc#971220f
```

**Comment by stevelizcano** [comment]
Thanks for the update!  🙏

We don't need data channel, just video and audio for now, so this will be perfect. Thank you! Let me know if there is anything I can do to help test it.

**Comment by steelbrain** [comment]
@slycoder This PR should be ready for review, can you please take a look when available?

**Pull request merged**
