### PR TITLE
Dominant speaker enabled feature

### PR DESCRIPTION
**Pull request by remigijusbalc**
This feature implements ios/android twilio dominant speaker handlers

### CODE REVIEW

**Review by slycoder — APPROVED** [review]
Looks great, awesome!  Thank you so much for this contribution!

**Comment by RobertStuff** [comment]
Good day. Is there any examples on how to use this? thanks

**Comment by remigijusbalc** [comment]
Just pass "dominantSpeakerEnabled" prop to connect options and add handler called "onDominantSpeakerDidChange" to TwilioVideo component

**Comment by RobertStuff** [comment]
Thanks @remigijusbalc

**Pull request merged**
