### PR TITLE
feat: Allow user to share screen on iOS through In app capture method 

### PR DESCRIPTION
**Pull request by Hamawis**
Addressing  #535

### CODE REVIEW

**Comment by Aleksandern** [comment]
Hello.
Any chance to merge this PR?

**Comment by Hamawis** [comment]
@Aleksandern you can use my forked repo if you need it urgent.

**Comment by Aleksandern** [comment]
Hi @Hamawis 
Is there any instruction about how to make it work? 
I think it's not enough just to enable `screenShare={true}`.

**Comment by Hamawis** [comment]
Oh sorry i forgot to update Readme file. Let me update it and meanwhile you can take look into example project "Example/index.js" file. You don't need "screenshare" prop.

**Comment by Aleksandern** [comment]
@Hamawis 
Should I do any additional steps for my project on Xcode?

**Comment by Aleksandern** [comment]
@Hamawis 
As I understand I only can share my application's screens, right? And I can not share screens outside of my application, such as the Home Screen or other applications?

**Comment by hamzaawais96** [comment]
@Aleksandern yes this PR is specifically for in-app capture. If we have to share the screen outside the app we have to use the broadcast extension method. I am working on it soon i will create PR for that as well.

**Comment by Aleksandern** [comment]
@Hamawis 
Thank you very much for your work. The broadcast method is more useful.

**Pull request merged**
