### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by luukschipperheyn**
My last pull request turned out to have some problems. This fixes them.

### CODE REVIEW

**Comment by luukschipperheyn** [comment]
also fixes https://github.com/blackuy/react-native-twilio-video-webrtc/issues/226

**Comment by slycoder** [comment]
Thanks for the quick turnaround!

**Comment by luukschipperheyn** [comment]
I hope you'll excuse the sloppiness. It was my first pull request ever :sweat_smile:

**Comment by slycoder** [comment]
No worries; your contributions are welcome!

**Pull request merged**
