### PR TITLE
[Expo Compatibility] - Add support for Expo Config Plugin

### PR DESCRIPTION
**Pull request by JonatanSalas**
**This PR is a draft on support for Expo Config Plugin.** 

**By now the current state is a 90% of advance**, I'm currently facing testing with some expo projects to see if it works as expected and also working on how to write a test suite to check all the cases. 

This Plugin is intended to help those using Expo to avoid ejecting their app or rely on pre-build. The core idea is to simplify the pain it takes to setup the library.

The Plugin is a run once plugin that perform the following steps:

#### On Android

1. Add support for `Camera`, `Audio` and `Recording Settings` permissions. 
2. Add support for `Java 1.8 compatibility`.
3. Add support for `pro-guard` rules.

#### On iOS

1. Add support for setting the Podfile target to `11.0`.
2. Add support for setting `NSCameraUsageDescription` and `NSMicrophoneUsageDescription` to the `Info.plist`.

I hope this helps those projects using Expo to improve their DX when working with this library.

### CODE REVIEW

**Comment by slycoder** [comment]
Hi @JonatanSalas , this seems like a positive direction for the package.  I know you mentioned in your initial comment that you saw this as a draft; I'm wondering when you think it'll be at the point where it's worth deploying.  The risk seems low so I'm open to merging as is .

**Comment by JonatanSalas** [comment]
Hi @slycoder! I've been testing the code and it seems working right 🙌 . 

The only thing that is left is the update of pod target, I've to perform a previous validation instead of applying a fixed version and I'm still looking on how to do so. **But I think we can work that on another PR.**

Let me know if that's right for you!

**Comment by JonatanSalas** [comment]
Hi @slycoder! Hope you're doing well. I would like to know the state of this PR, if you're intended to merge it!

**Review by slycoder — APPROVED** [review]

**Comment by slycoder** [comment]
Sorry that this fell off my radar!  Went ahead and merged.

**Comment by JonatanSalas** [comment]
Hi @slycoder! No trouble, thank you very much! Let me know when the release is available!

**Comment by slycoder** [comment]
Done

**Comment by prj786** [comment]
Hello I am trying to use this package with expo, but i got an error: can not find module 'babel-plugin-react-native-twilio-video-webrtc'. i used guide provided by you from github. did i miss something?

**Comment by prj786** [comment]
@JonatanSalas

**Pull request merged**
