### PR TITLE
Feature/android multiparty

### PR DESCRIPTION
**Pull request by georgewwindsor**
The existing android code uses a single "participantTrack" to contain incoming tracks. This causes 2 problems:

1) current android code is only 1-to-1. 
2) the current android code gets" disconnected" from the server because it screws up the bitrate when you replace the video with the next incoming person.

I have modified the library to allow multiple android users on stage at once. This required routing the trackId through the android component, which was previously not being done.

i additionally updated the android TWILIO dependency from 1.0.1 to 1.3.8 because...well it was just severely outdated. It now matches the current IOS.

Please Review and test on 3+ devices, one of the being android. if you have any suggestions or request, please let me know and i will be happy to make the changes.

### CODE REVIEW

**Comment by bilby91** [comment]
@georgewwindsor Thanks for the contribution! Will try to get into reviewing this PR as soon as I can! In the meantime, can you squash all the commits ?

Thanks!

**Comment by georgewwindsor** [comment]
@bilby91 i will circle back and cleanup after the holidays :) have a good one.

**Comment by bilby91** [comment]
@georgewwindsor Great! Ping me when you are back!

**Comment by cipriancaba** [comment]
Hey guys, I'm having big issues with the feature parity on android.. If you guys want, I can squash all the commits so we can have this merged.. Cheers

**Comment by slycoder** [comment]
@georgewwindsor  Thanks!  Yeah, if you squash we should be able to get this in quickly.

**Comment by cipriancaba** [comment]
Didn't really had access to the original fork so I created #76 with the squashed commit and a small error fixed

**Comment by georgewwindsor** [comment]
very nice. In some instances of debugging, i have had to make this modification to  twiliovideoparticipantview.android.js. I think this should not be necessary for most people. has something to do with testing or some such.

TwilioRemotePreview.propTypes = {
    trackId: PropTypes.string,
    renderToHardwareTextureAndroid: PropTypes.string,

    onLayout: PropTypes.string,

    accessibilityLiveRegion: PropTypes.string,

    accessibilityComponentType: PropTypes.string,

    importantForAccessibility: PropTypes.string,

    accessibilityLabel: PropTypes.string,
    nativeID: PropTypes.string,
    testID: PropTypes.string,
}

**Comment by slycoder** [comment]
Closing this one in favor of #82

**Pull request closed without merging**
