### PR TITLE
Upgrade twilio video version on iOS

### LINKED ISSUE #161: Iphone X TwilioVideoLocalView Image is Distorted
### Steps to reproduce
1. Use demo example on an iPhone X
2. Open local video track 

### Expected behaviour

The local video track should render appropriately for all iPhone types. 

### Actual behaviour

The local video track is distorted for the user, renders horizontally. This behavior only happens with iPhone X so far. However, the video renders correctly for other chat participants. And when other participants join the chat, the video rerenders appropriately.

### Environment
- **Node.js version**: v10.11.0
- **React Native version**: 0.57.1
- **React Native platform + platform version**: iOS 12.1 

### react-native-twilio-video-webrtc
**Version**: "master"

screen shot 2018-12-19 at 12 36 26 pm

### PR DESCRIPTION
**Pull request by slycoder**
Fixes #161

### CODE REVIEW

**Comment by viktorlarsson** [comment]
Is this going to be merged? :)

**Comment by slycoder** [comment]
🤞

**Comment by viktorlarsson** [comment]
Hehe, I just tried out TwilioVideo 2.7.0 and that seems to work as well. Do you want me to create a new PR and rebase master?

**Comment by slycoder** [comment]
Sure thing.  If you create the PR then I can merge it.

**Comment by slycoder** [comment]
Closing this one.

**Comment by slycoder** [comment]
(In favor of #187 )

**Pull request closed without merging**
