### PR TITLE
Start importing android files

### PR DESCRIPTION
**Pull request by slycoder**
This is a crude copy of all of the android files from the android port
of react-native-twilio-video-webrtc.

1.) Some of these files need to be cleaned up (and possibly removed)
2.) These conform to the older interface of the package.
3.) JS files are still missing.

### CODE REVIEW

**Comment by rajesh1158** [comment]
"These conform to the older interface of the package."  --> From the branch upgrade-1.0.1?

**Comment by rajesh1158** [comment]
@slycoder  Getting an error with the latest code base: undefined is not an object (evaluating TWVideoModule.startLocalVideo).

**Comment by rajesh1158** [comment]
@slycoder I'll check back in my morning time to see if all the changes to make the app work are integrated. Thanks for the good work.

**Comment by rajesh1158** [comment]
@slycoder  Also, it would be great if you could provide an example js file which demonstrates call start / end and audio mute/unmute examples. TIA.

**Comment by rajesh1158** [comment]
No. I got an error: Illegal number of arguments passed to the 'updateHotspot' command. I narrowed down to the cause of this error as the receiveCommand() function not being overridden from the SimpleViewManager class (base class), and so the command ids 1 and 2 are being passed to the base class. Not sure how to fix this.

**Comment by slycoder** [comment]
@bilby91 @gastonmorixe : Ok, this seems to be at least building ok for me.

As I mentioned, this doesn't support all the functionality of the iOS package yet (e.g. it assumes only one remote participant), but it might be worth merging this in since it should have no impact on the existing iOS functionality and it'll give a good starting point for multiple people to work on getting the android side up to snuff.

**Comment by bilby91** [comment]
@slycoder Sorry for the delay! Can you squash the commits ? The example project is working for you ? Awesome job men, other people are really interested in this!

**Comment by slycoder** [comment]
@bilby91 I've gone ahead and squashed the commits.  It doesn't quite work yet with the example project.  We can either merge as is and I can followup or I can continue to add to this branch.  I think I'll have time to make progress on this later this week perhaps but it would be useful to just merge this to master so that more people can work on it.

**Comment by bilby91** [comment]
Good. I'll merge so people can start playing with it. Let me know!

**Pull request merged**
