### PR TITLE
register ON_FRAME_DIMENSIONS_CHANGED to TwilioRemotePreviewManager

### LINKED ISSUE #361: Unsupported top level event type - OnFrameDimensionsChanged
### Steps to reproduce
when I render `TwilioVideoParticipantView` with particular width and height style, getting this error.

1. First showing the remote video as thumbnail view.
2. Once check on the thumbnail view changing it to full screen.

Failing at first step itslf. Getting an error after a remote video is rendered, (fully stretched). Not fit with thumbnail view port.

Screenshot_20200803-190749

### Expected behaviour
It's should render based on given layout style.

### Actual behaviour
Its throw `onFrameDimensionsChanged`  error. Happening only in **android**.

### react-native-twilio-video-webrtc
**Version**: master

### PR DESCRIPTION
**Pull request by luukschipperheyn**
fixes #361 
I haven't tested if this breaks #343 since my app only supports portrait mode.

### CODE REVIEW

**Review by slycoder — CHANGES_REQUESTED** [review]
LGTM, thanks for digging into this and fixing the issue!  Just one ask, could you remove the change from the other PR from this one?

**Comment by krisbaum74** [comment]
Hi does anybody know if this will be fixed soon?  or if there's a workaround?

**Comment by gabrielgc** [comment]
I'm not a specialist here, but I think @luukschipperheyn already did the requested changes. At least I couldn't find any references from https://github.com/blackuy/react-native-twilio-video-webrtc/pull/343/ in this PR

**Comment by slycoder** [comment]
I'll go ahead and fix up the PR and merge this in.

**Review by slycoder — APPROVED** [review]

**Pull request merged**
