### PR TITLE
Enable use without adding to Podfile

### PR DESCRIPTION
**Pull request by amsul**
As amazingly useful as this project has been for me, it has caused serious issues in using with Fastlane and my Podfile while having `use_frameworks` enabled.

So, I created an XCode project for this library, which (in my opinion) simplifies the setup on iOS.

If you choose to merge this, the setup process will be something like this:

1. Add `pod 'TwilioVideo'` to your Podfile
2. Add `RNTwilioVideo.xcodeproj` to the Libraries directory in your project
3. Add `libRNTwilioVideo.a` to the "Linked Frameworks and Libraries"

A further improvement would be to make it so you can just run `react-native link react-native-twilio-video-webrtc` and it performs the 3 steps above.

### CODE REVIEW

**Comment by bilby91** [comment]
Hey! 

Thanks for the PR. I'm curious with what problems you have encountered using fastlane. Can you provide more information please?

If we are going to support two ways of installing we will need to add some information on the Readme. 

Also, probably the xcode project name should be named RNTwilioVideoWebRTC.

Thanks!

**Comment by amsul** [comment]
@bilby91 I wasn't able to build at all using the setup in the Readme until I switched off `use_frameworks` in my Podfile. This worked fine in development mode but archiving the app or shipping with Fastlane (which archives it as well) would result in linking errors.

From my experience with RN libraries, any that suggest adding `React` and `yoga` as a pod referencing `node_modules` leads to problems with builds or bundling with Fastlane.

Here's another example https://github.com/getsentry/react-native-sentry/issues/344 where I used this same approach instead of modifying the Podfile.

Regarding two ways of installing, yes the old way will still work but I would suggest that should be deprecated and eventually removed from the docs to avoid confusion in the future.

**Comment by amsul** [comment]
Oh and yeah, I can totally rename the XCode project if you like..

**Comment by bilby91** [comment]
Haven't had the chance to use RN in with Fastlane yet! 

Can you do the rename and add installation steps in the REDME ? We can deprecate the old one!

**Comment by amsul** [comment]
@bilby91 just updated it and confirmed that it works on my project :)

**Comment by bilby91** [comment]
@amsul what would it take to make it work with the link command?

Thanks for the contribution!

**Comment by amsul** [comment]
🙏 

Not entirely sure of the specifics off the top of my head, but it's done using an entry for `rnpm` in  `package.json` that looks something like:

```json
{ "rnpm": { "ios": { "project": ".../a.xcodeproj" } } }
```

**Comment by alfonsosn** [comment]
@amsul How do you about creating an Xcode project? I'm looking at using `V2` branch right now, and they have still the old setup and the project is not really building for me. I'm thinking of applying your solution to that branch as well, should I merge this commit or should I create the Xcode project with the current state of the working branch?

**Comment by amsul** [comment]
@alfonsosn honestly, i don't recall the exact steps but it was very manual. If it's possible, I'd suggest merging this commit and ensuring everything new in v2 is in the XCode project.

**Pull request merged**
